### ISSUE TITLE
5.10有问题（表大小写问题）

### ISSUE THREAD

**Issue by johnnychen** [yuque/confluence2lark#1]
![image](https://user-images.githubusercontent.com/1297278/35031979-23ae3cb2-fba0-11e7-90db-b652a6a9b9d5.png)

 confluence 5.10里，表都是大写, 没有`content`表，只有`CONTENT`表

**Comment by johnnychen** [comment]
![image](https://user-images.githubusercontent.com/1297278/35032030-5751b7ce-fba0-11e7-824a-8fd43182443f.png)

**Comment by huacnlee** [comment]
你可以尝试修改 MySQL 配置文件:

```conf
lower_case_table_names = 1
```

**Comment by johnnychen** [comment]
好的，谢谢

**Comment by johnnychen** [comment]
试了下，还有问题，原因是，改上述配置后只会对未来新建表起作用。。。

https://www.cnblogs.com/kevingrace/p/6150748.html

我们把所有表手动修改成小写了

**Comment by huacnlee** [comment]
@johnnychen 这样，我修改一下，发布一个，查询用大写字母的

**Comment by huacnlee** [comment]
https://github.com/yuque/confluence2lark/releases/tag/1.0.2

你试试

**Comment by johnnychen** [comment]
我们把所有表手动修改成小写了。。
所以就没试，已经可以了哈，谢谢

**Comment by huacnlee** [comment]
@johnnychen 已经迁移成功了么？
