### ISSUE TITLE
删除后的知识库在搜索时还会出现

### ISSUE THREAD

**Issue by johnnychen** [yuque/confluence2lark#5]
因为第一次迁移图片失败，用v1.1新版本迁移时把原先的删除了，重新迁移了一下，图片正常

但，搜索时，原先删除的知识库还能被索引到，截图：

![image](https://user-images.githubusercontent.com/1297278/35092531-ac2dc62c-fc7a-11e7-9778-0e64725a7914.png)

很奇怪的现象，对应的链接地址直接是`https://cathay.yuque.com/404`，而不是原地址访问后302到404

**Comment by huacnlee** [comment]
等我今天修复一下

**Comment by huacnlee** [comment]
问题已经解决了，你尝试再次搜索那个，会自动修正有问题的数据，下次就搜索不到了

之前的删除同步搜索引擎有个 Bug，现在已经解决掉了
